# Generated by Django 4.2 on 2023-04-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productify", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="employee", name="emplyee_id",),
        migrations.AddField(
            model_name="employee",
            name="employee_id",
            field=models.IntegerField(null=True),
        ),
    ]
