# Generated by Django 4.2 on 2023-04-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productify", "0002_remove_employee_emplyee_id_employee_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=35)),
            ],
        ),
    ]
