# Generated by Django 4.2 on 2023-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productify", "0003_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("reminder", models.BooleanField(default=False)),
                ("text", models.CharField(max_length=230)),
                ("day", models.CharField(max_length=300)),
            ],
        ),
    ]
